### ISSUE TITLE
Way to mix in net/scp with sessions?

### ISSUE THREAD

**Issue by rberger** [sosedoff/net-ssh-session#1]
Is there an easy way to reuse a Net::SSH::Session instance to be able to mix in Net::SCP commands or otherwise do scp with an existing session?

**Comment by sosedoff** [comment]
Not sure if thats possible, let me try to experiment.

**Comment by sosedoff** [comment]
Should work, example: 

``` ruby
require 'net/ssh/session'
require 'net/scp'

s = Net::SSH::Session.new('hostname', 'user')
s.open
s.connection.scp.upload!("/tmp/foobar", "/tmp/foobar")
s.close
```
